test:
  image: node:13-buster-slim
  script:
    - apt install docker docker-compose -y
    - docker build -t alpr:latest ./express-openalpr-server
    - docker create --name alpr1 alpr:latest
    - docker start alpr1
    - npm install --prefix backend
    - npm run --prefix compiel
    - npm install --prefix frontend
    - bash test_all.sh
